export const FETCH_COMPANY_ADD = '@AUTH/FETCH_COMPANY_ADD';
export const FETCH_COMPANY_EDIT = '@AUTH/FETCH_COMPANY_EDIT';
export const FETCH_COMPANY_DELETE = '@AUTH/FETCH_COMPANY_DELETE';
export const FETCH_COMPANIES = '@AUTH/FETCH_COMPANIES';
export const FETCH_COMPANY = '@AUTH/FETCH_COMPANY';
