export const FETCH_COMPANY_ADD = '@COMPANY/FETCH_COMPANY_ADD';
export const FETCH_COMPANY_EDIT = '@COMPANY/FETCH_COMPANY_EDIT';
export const FETCH_COMPANY_DELETE = '@COMPANY/FETCH_COMPANY_DELETE';
export const FETCH_COMPANIES = '@COMPANY/FETCH_COMPANIES';
export const FETCH_COMPANY = '@COMPANY/FETCH_COMPANY';
